### PR TITLE
Dct 509 remove rating object

### PR DESCRIPTION
**Pull request by Roznovjak**

### CODE REVIEW

**Comment by tigrangh** [comment]
buying_object::average_rating is used by gui application, can's simply get rid of it

**Comment by Roznovjak** [comment]
Where do we use it?

**Comment by tigrangh** [comment]
https://github.com/DECENTfoundation/DECENT-Network/blob/master/programs/gui_wallet/src/purchased_tab.cpp

void PurchasedTab::timeToUpdate
it's dealing with "search_my_purchases" as seen from PurchasedTab::getUpdateCommand

unfortunately compiler is not helping to find this relations, so we need to be more careful

**Comment by Roznovjak** [comment]
search_my_purchases returns buying_object_ex structs. This struct had two average ratings and I have removed one from buying_object.

**Comment by tigrangh** [comment]
buying_object_ex derives "average_rating" from buying_object, which is being used in DECENT application. it also has "rating" but that's different.

**Comment by Roznovjak** [comment]
yes, but buying_object_ex had 2 average_ratings. I removed one from buying_object.

**Pull request merged**
